"""initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-05-16

This migration creates the entire ReqGen database from scratch.
It replaces the original 01e9839b99df migration (which was an autogenerated
diff against a pre-existing DB and assumed tables already existed).

Chain after this:
  0001_initial_schema
      → 3654108b0423  (fix audit_log trigger + orphaned messages)
      → 354786d19932  (fix audit_log FK ON DELETE SET NULL)
      → c88763c8f6bb  (robustly re-drop/re-add audit_log FK)

After generating this file:
  1. Delete backend/database/migrations/versions/01e9839b99df_add_conversation_title.py
  2. Edit 3654108b0423 and set:  down_revision = '0001_initial_schema'
  3. On a fresh DB run:  alembic upgrade head
  4. Keep schema.sql as documentation only — Alembic is now the source of truth.
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial_schema"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # ── Extensions ────────────────────────────────────────────────────────────
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')

    # ── Enums ─────────────────────────────────────────────────────────────────
    op.execute("""
        CREATE TYPE user_role AS ENUM (
            'admin',
            'requirement_engineer',
            'domain_expert',
            'stakeholder',
            'viewer'
        )
    """)

    op.execute("""
        CREATE TYPE project_status AS ENUM (
            'active',
            'archived',
            'completed',
            'on_hold'
        )
    """)

    op.execute("""
        CREATE TYPE requirement_type AS ENUM (
            'functional',
            'non_functional',
            'constraint',
            'interface',
            'performance',
            'security',
            'usability',
            'reliability',
            'maintainability',
            'portability'
        )
    """)

    op.execute("""
        CREATE TYPE requirement_status AS ENUM (
            'draft',
            'under_review',
            'approved',
            'rejected',
            'deprecated',
            'implemented'
        )
    """)

    op.execute("""
        CREATE TYPE priority_level AS ENUM (
            'must_have',
            'should_have',
            'could_have',
            'wont_have'
        )
    """)

    op.execute("""
        CREATE TYPE conversation_status AS ENUM (
            'active',
            'completed',
            'abandoned'
        )
    """)

    op.execute("""
        CREATE TYPE message_sender AS ENUM (
            'user',
            'bot'
        )
    """)

    op.execute("""
        CREATE TYPE review_decision AS ENUM (
            'approved',
            'rejected',
            'needs_revision'
        )
    """)

    op.execute("""
        CREATE TYPE export_format AS ENUM (
            'json',
            'excel',
            'word',
            'pdf',
            'jira',
            'doors'
        )
    """)

    op.execute("""
        CREATE TYPE change_type AS ENUM (
            'created',
            'updated',
            'deleted',
            'status_changed',
            'priority_changed',
            'approved',
            'rejected'
        )
    """)

    op.execute("""
        CREATE TYPE nfr_category AS ENUM (
            'performance',
            'security',
            'usability',
            'reliability',
            'scalability',
            'maintainability',
            'portability',
            'availability',
            'compliance'
        )
    """)

    # ── TABLE 1: users ────────────────────────────────────────────────────────
    op.execute("""
        CREATE TABLE users (
            id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
            email         VARCHAR(255) NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            full_name     VARCHAR(255) NOT NULL,
            role          user_role NOT NULL DEFAULT 'stakeholder',
            is_active     BOOLEAN NOT NULL DEFAULT TRUE,
            last_login    TIMESTAMPTZ,
            created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    """)
    op.execute("CREATE INDEX idx_users_email ON users(email)")
    op.execute("CREATE INDEX idx_users_role  ON users(role)")

    # ── TABLE 2: projects ─────────────────────────────────────────────────────
    op.execute("""
        CREATE TABLE projects (
            id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
            name        VARCHAR(255) NOT NULL,
            description TEXT,
            domain      VARCHAR(100),
            status      project_status NOT NULL DEFAULT 'active',
            owner_id    UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
            created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    """)
    op.execute("CREATE INDEX idx_projects_owner  ON projects(owner_id)")
    op.execute("CREATE INDEX idx_projects_status ON projects(status)")

    # ── TABLE 3: project_members ──────────────────────────────────────────────
    op.execute("""
        CREATE TABLE project_members (
            id         UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
            project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
            user_id    UUID NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
            role       user_role NOT NULL DEFAULT 'stakeholder',
            joined_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE(project_id, user_id)
        )
    """)
    op.execute("CREATE INDEX idx_project_members_project ON project_members(project_id)")
    op.execute("CREATE INDEX idx_project_members_user    ON project_members(user_id)")

    # ── TABLE 4: conversations ────────────────────────────────────────────────
    # NOTE: includes the 'title' column added by add_conversation_title.sql /
    # migration 01e9839b99df — it is baked in here so the chain starts clean.
    op.execute("""
        CREATE TABLE conversations (
            id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
            project_id      UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
            user_id         UUID NOT NULL REFERENCES users(id)    ON DELETE RESTRICT,
            rasa_session_id VARCHAR(255) UNIQUE,
            status          conversation_status NOT NULL DEFAULT 'active',
            title           VARCHAR(200) NULL,
            context         JSONB NOT NULL DEFAULT '{}',
            started_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            ended_at        TIMESTAMPTZ,
            created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    """)
    op.execute("CREATE INDEX idx_conversations_project ON conversations(project_id)")
    op.execute("CREATE INDEX idx_conversations_user    ON conversations(user_id)")
    op.execute("CREATE INDEX idx_conversations_status  ON conversations(status)")

    # ── TABLE 5: messages ─────────────────────────────────────────────────────
    op.execute("""
        CREATE TABLE messages (
            id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
            conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
            sender          message_sender NOT NULL,
            content         TEXT NOT NULL,
            intent          VARCHAR(100),
            confidence      NUMERIC(5,4),
            entities        JSONB NOT NULL DEFAULT '[]',
            created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    """)
    op.execute("CREATE INDEX idx_messages_conversation ON messages(conversation_id)")
    op.execute("CREATE INDEX idx_messages_sender       ON messages(sender)")

    # ── TABLE 6: user_stories ─────────────────────────────────────────────────
    op.execute("""
        CREATE TABLE user_stories (
            id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
            project_id      UUID NOT NULL REFERENCES projects(id)      ON DELETE CASCADE,
            conversation_id UUID          REFERENCES conversations(id)  ON DELETE SET NULL,
            submitted_by    UUID NOT NULL REFERENCES users(id)          ON DELETE RESTRICT,
            raw_text        TEXT NOT NULL,
            domain_context  VARCHAR(100),
            goals           TEXT[],
            actors          TEXT[],
            constraints     TEXT[],
            metadata        JSONB NOT NULL DEFAULT '{}',
            processed       BOOLEAN NOT NULL DEFAULT FALSE,
            created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    """)
    op.execute("CREATE INDEX idx_user_stories_project   ON user_stories(project_id)")
    op.execute("CREATE INDEX idx_user_stories_processed ON user_stories(processed)")

    # ── TABLE 7: nlp_jobs ─────────────────────────────────────────────────────
    op.execute("""
        CREATE TABLE nlp_jobs (
            id                UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
            user_story_id     UUID NOT NULL REFERENCES user_stories(id) ON DELETE CASCADE,
            model_used        VARCHAR(100),
            spacy_output      JSONB NOT NULL DEFAULT '{}',
            transformer_output JSONB NOT NULL DEFAULT '{}',
            tokens            TEXT[],
            named_entities    JSONB NOT NULL DEFAULT '[]',
            dependency_parse  JSONB NOT NULL DEFAULT '{}',
            semantic_roles    JSONB NOT NULL DEFAULT '{}',
            processing_time_ms INTEGER,
            success           BOOLEAN NOT NULL DEFAULT FALSE,
            error_message     TEXT,
            created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    """)
    op.execute("CREATE INDEX idx_nlp_jobs_story   ON nlp_jobs(user_story_id)")
    op.execute("CREATE INDEX idx_nlp_jobs_success ON nlp_jobs(success)")

    # ── TABLE 8: requirements ─────────────────────────────────────────────────
    op.execute("""
        CREATE TABLE requirements (
            id                     UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
            project_id             UUID NOT NULL REFERENCES projects(id)    ON DELETE RESTRICT,
            user_story_id          UUID          REFERENCES user_stories(id) ON DELETE SET NULL,
            nlp_job_id             UUID          REFERENCES nlp_jobs(id)     ON DELETE SET NULL,

            req_id                 VARCHAR(50) NOT NULL,
            title                  VARCHAR(500) NOT NULL,
            statement              TEXT NOT NULL,
            type                   requirement_type NOT NULL,
            rationale              TEXT,
            fit_criterion          TEXT,
            originator             VARCHAR(255),

            status                 requirement_status NOT NULL DEFAULT 'draft',
            priority               priority_level NOT NULL DEFAULT 'should_have',
            version                INTEGER NOT NULL DEFAULT 1,
            is_current_version     BOOLEAN NOT NULL DEFAULT TRUE,

            business_value_score   SMALLINT CHECK (business_value_score  BETWEEN 1 AND 5),
            risk_score             SMALLINT CHECK (risk_score             BETWEEN 1 AND 5),
            cost_effort_score      SMALLINT CHECK (cost_effort_score      BETWEEN 1 AND 5),
            stakeholder_importance SMALLINT CHECK (stakeholder_importance BETWEEN 1 AND 5),
            weighted_score         NUMERIC(6,3),

            ambiguity_score        NUMERIC(5,4),
            completeness_score     NUMERIC(5,4),
            consistency_score      NUMERIC(5,4),
            testability_score      NUMERIC(5,4),
            overall_quality_score  NUMERIC(5,4),
            qa_issues              JSONB NOT NULL DEFAULT '[]',
            qa_confidence          NUMERIC(5,4),

            ai_generated           BOOLEAN NOT NULL DEFAULT TRUE,
            ai_confidence          NUMERIC(5,4),

            created_by             UUID REFERENCES users(id) ON DELETE SET NULL,
            created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),

            UNIQUE(project_id, req_id, version)
        )
    """)
    op.execute("CREATE INDEX idx_requirements_project  ON requirements(project_id)")
    op.execute("CREATE INDEX idx_requirements_status   ON requirements(status)")
    op.execute("CREATE INDEX idx_requirements_type     ON requirements(type)")
    op.execute("CREATE INDEX idx_requirements_priority ON requirements(priority)")
    op.execute("CREATE INDEX idx_requirements_current  ON requirements(is_current_version)")
    op.execute("CREATE INDEX idx_requirements_req_id   ON requirements(req_id)")

    # ── TABLE 9: nfr_details ──────────────────────────────────────────────────
    op.execute("""
        CREATE TABLE nfr_details (
            id                 UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
            requirement_id     UUID NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,
            nfr_category       nfr_category NOT NULL,
            metric             VARCHAR(255),
            target_value       VARCHAR(255),
            measurement_method TEXT,
            UNIQUE(requirement_id)
        )
    """)

    # ── TABLE 10: requirement_dependencies ───────────────────────────────────
    # dependency_type is NOT NULL (matches SQLAlchemy model after 01e9839b99df
    # made it non-nullable; we carry that forward here). Default still applies.
    op.execute("""
        CREATE TABLE requirement_dependencies (
            id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
            requirement_id  UUID NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,
            depends_on_id   UUID NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,
            dependency_type VARCHAR(50) NOT NULL DEFAULT 'depends_on',
            notes           TEXT,
            created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            CHECK (requirement_id != depends_on_id),
            UNIQUE(requirement_id, depends_on_id)
        )
    """)
    op.execute("CREATE INDEX idx_req_deps_req     ON requirement_dependencies(requirement_id)")
    op.execute("CREATE INDEX idx_req_deps_depends ON requirement_dependencies(depends_on_id)")

    # ── TABLE 11: reviews ─────────────────────────────────────────────────────
    op.execute("""
        CREATE TABLE reviews (
            id             UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
            requirement_id UUID NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,
            reviewer_id    UUID NOT NULL REFERENCES users(id)        ON DELETE RESTRICT,
            decision       review_decision NOT NULL,
            comments       TEXT,
            suggested_changes TEXT,
            reviewed_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    """)
    op.execute("CREATE INDEX idx_reviews_requirement ON reviews(requirement_id)")
    op.execute("CREATE INDEX idx_reviews_reviewer    ON reviews(reviewer_id)")
    op.execute("CREATE INDEX idx_reviews_decision    ON reviews(decision)")

    # ── TABLE 12: audit_log ───────────────────────────────────────────────────
    # FK on requirement_id uses ON DELETE SET NULL (applied in 3654108b0423 /
    # c88763c8f6bb) — baked in here from the start so those migrations become
    # no-ops on fresh installs (they guard with DROP IF EXISTS / DO $$ blocks
    # so they are safe to run anyway).
    # id uses gen_random_uuid() default (fix from 3654108b0423) baked in here.
    op.execute("""
        CREATE TABLE audit_log (
            id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            project_id     UUID NOT NULL REFERENCES projects(id)      ON DELETE CASCADE,
            requirement_id UUID          REFERENCES requirements(id)   ON DELETE SET NULL,
            changed_by     UUID          REFERENCES users(id)          ON DELETE SET NULL,
            change_type    change_type NOT NULL,
            field_changed  VARCHAR(100),
            old_value      TEXT,
            new_value      TEXT,
            change_reason  TEXT,
            snapshot       JSONB,
            created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    """)
    op.execute("CREATE INDEX idx_audit_project     ON audit_log(project_id)")
    op.execute("CREATE INDEX idx_audit_requirement ON audit_log(requirement_id)")
    op.execute("CREATE INDEX idx_audit_changed_by  ON audit_log(changed_by)")
    op.execute("CREATE INDEX idx_audit_created_at  ON audit_log(created_at)")

    # ── TABLE 13: traceability_matrix ─────────────────────────────────────────
    # UNIQUE is on (requirement_id) only — not (project_id, requirement_id).
    # The schema.sql had UNIQUE(project_id, requirement_id) but 01e9839b99df
    # dropped that and replaced it with UNIQUE(requirement_id). We use the
    # corrected version here so the model and DB stay in sync.
    op.execute("""
        CREATE TABLE traceability_matrix (
            id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
            project_id          UUID NOT NULL REFERENCES projects(id)      ON DELETE CASCADE,
            requirement_id      UUID NOT NULL REFERENCES requirements(id)   ON DELETE CASCADE,
            user_story_id       UUID          REFERENCES user_stories(id)   ON DELETE SET NULL,
            test_case_ref       VARCHAR(255),
            implementation_ref  VARCHAR(255),
            verification_method VARCHAR(100),
            verified            BOOLEAN NOT NULL DEFAULT FALSE,
            notes               TEXT,
            created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE(requirement_id)
        )
    """)
    op.execute("CREATE INDEX idx_rtm_project     ON traceability_matrix(project_id)")
    op.execute("CREATE INDEX idx_rtm_requirement ON traceability_matrix(requirement_id)")

    # ── TABLE 14: exports ─────────────────────────────────────────────────────
    op.execute("""
        CREATE TABLE exports (
            id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
            project_id      UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
            exported_by     UUID NOT NULL REFERENCES users(id)    ON DELETE RESTRICT,
            format          export_format NOT NULL,
            file_name       VARCHAR(255),
            file_path       TEXT,
            requirement_ids UUID[],
            export_config   JSONB NOT NULL DEFAULT '{}',
            created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    """)
    op.execute("CREATE INDEX idx_exports_project ON exports(project_id)")

    # ── FUNCTION + TRIGGER: updated_at maintenance ────────────────────────────
    op.execute("""
        CREATE OR REPLACE FUNCTION update_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER trg_users_updated_at
            BEFORE UPDATE ON users
            FOR EACH ROW EXECUTE FUNCTION update_updated_at()
    """)
    op.execute("""
        CREATE TRIGGER trg_projects_updated_at
            BEFORE UPDATE ON projects
            FOR EACH ROW EXECUTE FUNCTION update_updated_at()
    """)
    op.execute("""
        CREATE TRIGGER trg_requirements_updated_at
            BEFORE UPDATE ON requirements
            FOR EACH ROW EXECUTE FUNCTION update_updated_at()
    """)
    op.execute("""
        CREATE TRIGGER trg_rtm_updated_at
            BEFORE UPDATE ON traceability_matrix
            FOR EACH ROW EXECUTE FUNCTION update_updated_at()
    """)

    # ── FUNCTION + TRIGGER: auto-generate req_id ──────────────────────────────
    op.execute("""
        CREATE OR REPLACE FUNCTION generate_req_id()
        RETURNS TRIGGER AS $$
        DECLARE
            prefix     VARCHAR(10);
            next_num   INTEGER;
            padded_num VARCHAR(5);
        BEGIN
            prefix := CASE NEW.type
                WHEN 'functional'      THEN 'FR'
                WHEN 'non_functional'  THEN 'NFR'
                WHEN 'constraint'      THEN 'CON'
                WHEN 'interface'       THEN 'IFR'
                WHEN 'performance'     THEN 'PER'
                WHEN 'security'        THEN 'SEC'
                WHEN 'usability'       THEN 'USR'
                WHEN 'reliability'     THEN 'REL'
                WHEN 'maintainability' THEN 'MNT'
                WHEN 'portability'     THEN 'PRT'
                ELSE 'REQ'
            END;

            SELECT COUNT(*) + 1
            INTO next_num
            FROM requirements
            WHERE project_id = NEW.project_id
              AND type = NEW.type;

            padded_num := LPAD(next_num::TEXT, 3, '0');
            NEW.req_id := prefix || '-' || padded_num;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER trg_generate_req_id
            BEFORE INSERT ON requirements
            FOR EACH ROW
            WHEN (NEW.req_id IS NULL OR NEW.req_id = '')
            EXECUTE FUNCTION generate_req_id()
    """)

    # ── FUNCTION + TRIGGER: audit log (fixed version from 3654108b0423) ───────
    # Uses gen_random_uuid() explicitly in every INSERT branch so the trigger
    # never relies solely on the column default. This is the corrected version
    # — no need for the old broken trigger to exist even briefly.
    op.execute("""
        CREATE OR REPLACE FUNCTION log_requirement_changes()
        RETURNS TRIGGER AS $$
        BEGIN
            IF TG_OP = 'INSERT' THEN
                INSERT INTO audit_log (
                    id, project_id, requirement_id, changed_by,
                    change_type, snapshot
                ) VALUES (
                    gen_random_uuid(),
                    NEW.project_id, NEW.id, NEW.created_by,
                    'created', row_to_json(NEW)
                );

            ELSIF TG_OP = 'UPDATE' THEN
                IF OLD.status IS DISTINCT FROM NEW.status THEN
                    INSERT INTO audit_log (
                        id, project_id, requirement_id, change_type,
                        field_changed, old_value, new_value, snapshot
                    ) VALUES (
                        gen_random_uuid(),
                        NEW.project_id, NEW.id, 'status_changed',
                        'status', OLD.status::TEXT, NEW.status::TEXT, row_to_json(NEW)
                    );
                END IF;

                IF OLD.priority IS DISTINCT FROM NEW.priority THEN
                    INSERT INTO audit_log (
                        id, project_id, requirement_id, change_type,
                        field_changed, old_value, new_value, snapshot
                    ) VALUES (
                        gen_random_uuid(),
                        NEW.project_id, NEW.id, 'priority_changed',
                        'priority', OLD.priority::TEXT, NEW.priority::TEXT, row_to_json(NEW)
                    );
                END IF;

                IF OLD.statement IS DISTINCT FROM NEW.statement
                    OR OLD.title IS DISTINCT FROM NEW.title THEN
                    INSERT INTO audit_log (
                        id, project_id, requirement_id, change_type,
                        field_changed, snapshot
                    ) VALUES (
                        gen_random_uuid(),
                        NEW.project_id, NEW.id, 'updated',
                        'statement/title', row_to_json(NEW)
                    );
                END IF;

            ELSIF TG_OP = 'DELETE' THEN
                INSERT INTO audit_log (
                    id, project_id, requirement_id, change_type, snapshot
                ) VALUES (
                    gen_random_uuid(),
                    OLD.project_id, OLD.id, 'deleted', row_to_json(OLD)
                );
            END IF;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER trg_audit_requirements
            AFTER INSERT OR UPDATE OR DELETE ON requirements
            FOR EACH ROW EXECUTE FUNCTION log_requirement_changes()
    """)


def downgrade() -> None:
    # ── Triggers ──────────────────────────────────────────────────────────────
    op.execute("DROP TRIGGER IF EXISTS trg_audit_requirements      ON requirements")
    op.execute("DROP TRIGGER IF EXISTS trg_generate_req_id         ON requirements")
    op.execute("DROP TRIGGER IF EXISTS trg_rtm_updated_at          ON traceability_matrix")
    op.execute("DROP TRIGGER IF EXISTS trg_requirements_updated_at ON requirements")
    op.execute("DROP TRIGGER IF EXISTS trg_projects_updated_at     ON projects")
    op.execute("DROP TRIGGER IF EXISTS trg_users_updated_at        ON users")

    # ── Functions ─────────────────────────────────────────────────────────────
    op.execute("DROP FUNCTION IF EXISTS log_requirement_changes()")
    op.execute("DROP FUNCTION IF EXISTS generate_req_id()")
    op.execute("DROP FUNCTION IF EXISTS update_updated_at()")

    # ── Tables (reverse FK order) ─────────────────────────────────────────────
    op.execute("DROP TABLE IF EXISTS exports                  CASCADE")
    op.execute("DROP TABLE IF EXISTS traceability_matrix      CASCADE")
    op.execute("DROP TABLE IF EXISTS audit_log                CASCADE")
    op.execute("DROP TABLE IF EXISTS reviews                  CASCADE")
    op.execute("DROP TABLE IF EXISTS requirement_dependencies CASCADE")
    op.execute("DROP TABLE IF EXISTS nfr_details              CASCADE")
    op.execute("DROP TABLE IF EXISTS requirements             CASCADE")
    op.execute("DROP TABLE IF EXISTS nlp_jobs                 CASCADE")
    op.execute("DROP TABLE IF EXISTS user_stories             CASCADE")
    op.execute("DROP TABLE IF EXISTS messages                 CASCADE")
    op.execute("DROP TABLE IF EXISTS conversations            CASCADE")
    op.execute("DROP TABLE IF EXISTS project_members          CASCADE")
    op.execute("DROP TABLE IF EXISTS projects                 CASCADE")
    op.execute("DROP TABLE IF EXISTS users                    CASCADE")

    # ── Enums ─────────────────────────────────────────────────────────────────
    op.execute("DROP TYPE IF EXISTS nfr_category")
    op.execute("DROP TYPE IF EXISTS change_type")
    op.execute("DROP TYPE IF EXISTS export_format")
    op.execute("DROP TYPE IF EXISTS review_decision")
    op.execute("DROP TYPE IF EXISTS message_sender")
    op.execute("DROP TYPE IF EXISTS conversation_status")
    op.execute("DROP TYPE IF EXISTS priority_level")
    op.execute("DROP TYPE IF EXISTS requirement_status")
    op.execute("DROP TYPE IF EXISTS requirement_type")
    op.execute("DROP TYPE IF EXISTS project_status")
    op.execute("DROP TYPE IF EXISTS user_role")