"""add_conversation_title

Revision ID: 01e9839b99df
Revises: 
Create Date: 2026-05-11 21:43:51.781224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01e9839b99df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_audit_changed_by'), table_name='audit_log')
    op.drop_index(op.f('idx_audit_created_at'), table_name='audit_log')
    op.drop_index(op.f('idx_audit_project'), table_name='audit_log')
    op.drop_index(op.f('idx_audit_requirement'), table_name='audit_log')
    op.add_column('conversations', sa.Column('title', sa.String(length=200), nullable=True))
    op.alter_column('conversations', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversations', 'status',
               existing_type=postgresql.ENUM('active', 'completed', 'abandoned', name='conversation_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversations', 'context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=False)
    op.drop_index(op.f('idx_conversations_project'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_status'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_user'), table_name='conversations')
    op.alter_column('exports', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('exports', 'export_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=False)
    op.drop_index(op.f('idx_exports_project'), table_name='exports')
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('messages', 'entities',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=False)
    op.drop_index(op.f('idx_messages_conversation'), table_name='messages')
    op.drop_index(op.f('idx_messages_sender'), table_name='messages')
    op.alter_column('nfr_details', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('nlp_jobs', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('nlp_jobs', 'spacy_output',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=False)
    op.alter_column('nlp_jobs', 'transformer_output',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=False)
    op.alter_column('nlp_jobs', 'named_entities',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=False)
    op.alter_column('nlp_jobs', 'dependency_parse',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=False)
    op.alter_column('nlp_jobs', 'semantic_roles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=False)
    op.alter_column('nlp_jobs', 'success',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_nlp_jobs_story'), table_name='nlp_jobs')
    op.drop_index(op.f('idx_nlp_jobs_success'), table_name='nlp_jobs')
    op.alter_column('project_members', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('project_members', 'role',
               existing_type=postgresql.ENUM('admin', 'requirement_engineer', 'domain_expert', 'stakeholder', 'viewer', name='user_role'),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_project_members_project'), table_name='project_members')
    op.drop_index(op.f('idx_project_members_user'), table_name='project_members')
    op.alter_column('projects', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('active', 'archived', 'completed', 'on_hold', name='project_status'),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_projects_owner'), table_name='projects')
    op.drop_index(op.f('idx_projects_status'), table_name='projects')
    op.alter_column('requirement_dependencies', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('requirement_dependencies', 'dependency_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=False)
    op.drop_index(op.f('idx_req_deps_depends'), table_name='requirement_dependencies')
    op.drop_index(op.f('idx_req_deps_req'), table_name='requirement_dependencies')
    op.alter_column('requirements', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('requirements', 'status',
               existing_type=postgresql.ENUM('draft', 'under_review', 'approved', 'rejected', 'deprecated', 'implemented', name='requirement_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('requirements', 'priority',
               existing_type=postgresql.ENUM('must_have', 'should_have', 'could_have', 'wont_have', name='priority_level'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('requirements', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('requirements', 'is_current_version',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('requirements', 'qa_issues',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=False)
    op.alter_column('requirements', 'ai_generated',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_requirements_current'), table_name='requirements')
    op.drop_index(op.f('idx_requirements_priority'), table_name='requirements')
    op.drop_index(op.f('idx_requirements_project'), table_name='requirements')
    op.drop_index(op.f('idx_requirements_req_id'), table_name='requirements')
    op.drop_index(op.f('idx_requirements_status'), table_name='requirements')
    op.drop_index(op.f('idx_requirements_type'), table_name='requirements')
    op.alter_column('reviews', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_reviews_decision'), table_name='reviews')
    op.drop_index(op.f('idx_reviews_requirement'), table_name='reviews')
    op.drop_index(op.f('idx_reviews_reviewer'), table_name='reviews')
    op.alter_column('traceability_matrix', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('traceability_matrix', 'verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.drop_index(op.f('idx_rtm_project'), table_name='traceability_matrix')
    op.drop_index(op.f('idx_rtm_requirement'), table_name='traceability_matrix')
    op.drop_constraint(op.f('traceability_matrix_project_id_requirement_id_key'), 'traceability_matrix', type_='unique')
    op.create_unique_constraint(None, 'traceability_matrix', ['requirement_id'])
    op.alter_column('user_stories', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_stories', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=False)
    op.alter_column('user_stories', 'processed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_user_stories_processed'), table_name='user_stories')
    op.drop_index(op.f('idx_user_stories_project'), table_name='user_stories')
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'requirement_engineer', 'domain_expert', 'stakeholder', 'viewer', name='user_role'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_role'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'requirement_engineer', 'domain_expert', 'stakeholder', 'viewer', name='user_role'),
               server_default=sa.text("'stakeholder'::user_role"),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_index(op.f('idx_user_stories_project'), 'user_stories', ['project_id'], unique=False)
    op.create_index(op.f('idx_user_stories_processed'), 'user_stories', ['processed'], unique=False)
    op.alter_column('user_stories', 'processed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('user_stories', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               nullable=True)
    op.alter_column('user_stories', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_constraint(None, 'traceability_matrix', type_='unique')
    op.create_unique_constraint(op.f('traceability_matrix_project_id_requirement_id_key'), 'traceability_matrix', ['project_id', 'requirement_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_rtm_requirement'), 'traceability_matrix', ['requirement_id'], unique=False)
    op.create_index(op.f('idx_rtm_project'), 'traceability_matrix', ['project_id'], unique=False)
    op.alter_column('traceability_matrix', 'verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('traceability_matrix', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_index(op.f('idx_reviews_reviewer'), 'reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('idx_reviews_requirement'), 'reviews', ['requirement_id'], unique=False)
    op.create_index(op.f('idx_reviews_decision'), 'reviews', ['decision'], unique=False)
    op.alter_column('reviews', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_index(op.f('idx_requirements_type'), 'requirements', ['type'], unique=False)
    op.create_index(op.f('idx_requirements_status'), 'requirements', ['status'], unique=False)
    op.create_index(op.f('idx_requirements_req_id'), 'requirements', ['req_id'], unique=False)
    op.create_index(op.f('idx_requirements_project'), 'requirements', ['project_id'], unique=False)
    op.create_index(op.f('idx_requirements_priority'), 'requirements', ['priority'], unique=False)
    op.create_index(op.f('idx_requirements_current'), 'requirements', ['is_current_version'], unique=False)
    op.alter_column('requirements', 'ai_generated',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('requirements', 'qa_issues',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               nullable=True)
    op.alter_column('requirements', 'is_current_version',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('requirements', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('requirements', 'priority',
               existing_type=postgresql.ENUM('must_have', 'should_have', 'could_have', 'wont_have', name='priority_level'),
               server_default=sa.text("'should_have'::priority_level"),
               existing_nullable=False)
    op.alter_column('requirements', 'status',
               existing_type=postgresql.ENUM('draft', 'under_review', 'approved', 'rejected', 'deprecated', 'implemented', name='requirement_status'),
               server_default=sa.text("'draft'::requirement_status"),
               existing_nullable=False)
    op.alter_column('requirements', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_index(op.f('idx_req_deps_req'), 'requirement_dependencies', ['requirement_id'], unique=False)
    op.create_index(op.f('idx_req_deps_depends'), 'requirement_dependencies', ['depends_on_id'], unique=False)
    op.alter_column('requirement_dependencies', 'dependency_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'depends_on'::character varying"),
               nullable=True)
    op.alter_column('requirement_dependencies', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_index(op.f('idx_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('idx_projects_owner'), 'projects', ['owner_id'], unique=False)
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('active', 'archived', 'completed', 'on_hold', name='project_status'),
               server_default=sa.text("'active'::project_status"),
               existing_nullable=False)
    op.alter_column('projects', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_index(op.f('idx_project_members_user'), 'project_members', ['user_id'], unique=False)
    op.create_index(op.f('idx_project_members_project'), 'project_members', ['project_id'], unique=False)
    op.alter_column('project_members', 'role',
               existing_type=postgresql.ENUM('admin', 'requirement_engineer', 'domain_expert', 'stakeholder', 'viewer', name='user_role'),
               server_default=sa.text("'stakeholder'::user_role"),
               existing_nullable=False)
    op.alter_column('project_members', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_index(op.f('idx_nlp_jobs_success'), 'nlp_jobs', ['success'], unique=False)
    op.create_index(op.f('idx_nlp_jobs_story'), 'nlp_jobs', ['user_story_id'], unique=False)
    op.alter_column('nlp_jobs', 'success',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('nlp_jobs', 'semantic_roles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               nullable=True)
    op.alter_column('nlp_jobs', 'dependency_parse',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               nullable=True)
    op.alter_column('nlp_jobs', 'named_entities',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               nullable=True)
    op.alter_column('nlp_jobs', 'transformer_output',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               nullable=True)
    op.alter_column('nlp_jobs', 'spacy_output',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               nullable=True)
    op.alter_column('nlp_jobs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.alter_column('nfr_details', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_index(op.f('idx_messages_sender'), 'messages', ['sender'], unique=False)
    op.create_index(op.f('idx_messages_conversation'), 'messages', ['conversation_id'], unique=False)
    op.alter_column('messages', 'entities',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               nullable=True)
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_index(op.f('idx_exports_project'), 'exports', ['project_id'], unique=False)
    op.alter_column('exports', 'export_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               nullable=True)
    op.alter_column('exports', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_index(op.f('idx_conversations_user'), 'conversations', ['user_id'], unique=False)
    op.create_index(op.f('idx_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('idx_conversations_project'), 'conversations', ['project_id'], unique=False)
    op.alter_column('conversations', 'context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               nullable=True)
    op.alter_column('conversations', 'status',
               existing_type=postgresql.ENUM('active', 'completed', 'abandoned', name='conversation_status'),
               server_default=sa.text("'active'::conversation_status"),
               existing_nullable=False)
    op.alter_column('conversations', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_column('conversations', 'title')
    op.create_index(op.f('idx_audit_requirement'), 'audit_log', ['requirement_id'], unique=False)
    op.create_index(op.f('idx_audit_project'), 'audit_log', ['project_id'], unique=False)
    op.create_index(op.f('idx_audit_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('idx_audit_changed_by'), 'audit_log', ['changed_by'], unique=False)
    op.alter_column('audit_log', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    # ### end Alembic commands ###
